# Generated by Django 5.2.1 on 2025-05-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ('id',), 'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
    ]
