# Generated by Django 5.2.1 on 2025-06-09 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group', models.BooleanField(default=False, verbose_name='групповой чат')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='название чата')),
                ('users', models.ManyToManyField(related_name='chat_users', to=settings.AUTH_USER_MODEL, verbose_name='участники чата')),
            ],
            options={
                'verbose_name': ('чат',),
                'verbose_name_plural': 'чаты',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=2000, verbose_name='текст')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='дата отправки')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_chat', to='chats.chat', verbose_name='чат')),
                ('parent_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_parent', to='chats.message', verbose_name='ответ на сообщение')),
                ('sender', models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='message_sender', to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
            ],
            options={
                'verbose_name': ('сообщение',),
                'verbose_name_plural': 'сообщениея',
                'ordering': ('id',),
            },
        ),
    ]
