# Generated by Django 5.2.1 on 2025-06-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('id',), 'verbose_name': 'чат', 'verbose_name_plural': 'чаты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('id',), 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщениея'},
        ),
    ]
