# Generated by Django 5.2.1 on 2025-06-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chat_options_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('id',), 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
    ]
